steps:

- name: 'gcr.io/cloud-builders/npm:node-10.16.0-jessie'
  args: ['install']

# - name: 'gcr.io/cloud-builders/npm:node-10.16.0-jessie'
#   args: ['test', '--', '']

- name: 'gcr.io/cloud-builders/npm:node-10.16.0-jessie'
  args: [ 'run', 'build', '--' '--prod' ]
  env:
  - 'FIREBASE_API_KEY=${_FIREBASE_API_KEY}'

- name: 'gcr.io/[PROJECT_ID]/firebase'
  args: [ 'deploy', '--token', '"$FIREBASE_TOKEN"' ]
  env:
  - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}'
